version: "2.1"

services:

   processmaker:
     image: processmaker/processmaker:etrial
     ports:
       - "80:80"
     restart: always
     environment:
       WORKSPACE: trial
     networks:
      - pm-net

networks:
  pm-net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.150.0/24
